---
name: HTTP-MobileAgent-Plugin-RoamingZone
version: 0.0.1
author:
  - 'OHTSUKA Ko-hei <nene@kokogiko.net>'
abstract: 日本の携帯電話から国内/海外のアクセス地域情報を得る
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  version: 0
provides:
  HTTP::MobileAgent::Plugin::RoamingZone:
    file: lib/HTTP/MobileAgent/Plugin/RoamingZone.pm
    version: 0.0.1
  HTTP::MobileAgent::Plugin::RoamingZone::CodeHash:
    file: lib/HTTP/MobileAgent/Plugin/RoamingZone/CodeHash.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
